// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESC_TA.Models;

public partial class Country
{
    public string CountryId { get; set; }

    public string CountryName { get; set; }

    public int RegionId { get; set; }

    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();

    public virtual Region Region { get; set; }
}