// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESC_TA.Models;

public partial class Dependent
{
    public int DependentId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Relationship { get; set; }

    public int EmployeeId { get; set; }

    public virtual Employee Employee { get; set; }
}