// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESC_TA.Models;

public partial class Region
{
    public int RegionId { get; set; }

    public string RegionName { get; set; }

    public virtual ICollection<Country> Countries { get; set; } = new List<Country>();
}